// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RocketPoolNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RocketPoolNodesRequest) Reset() {
	*x = RocketPoolNodesRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RocketPoolNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RocketPoolNodesRequest) ProtoMessage() {}

func (x *RocketPoolNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RocketPoolNodesRequest.ProtoReflect.Descriptor instead.
func (*RocketPoolNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type RocketPoolNodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       [][]byte               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RocketPoolNodes) Reset() {
	*x = RocketPoolNodes{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RocketPoolNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RocketPoolNodes) ProtoMessage() {}

func (x *RocketPoolNodes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RocketPoolNodes.ProtoReflect.Descriptor instead.
func (*RocketPoolNodes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *RocketPoolNodes) GetNodeIds() [][]byte {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type OdaoNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OdaoNodesRequest) Reset() {
	*x = OdaoNodesRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OdaoNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdaoNodesRequest) ProtoMessage() {}

func (x *OdaoNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdaoNodesRequest.ProtoReflect.Descriptor instead.
func (*OdaoNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

type OdaoNodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       [][]byte               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OdaoNodes) Reset() {
	*x = OdaoNodes{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OdaoNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdaoNodes) ProtoMessage() {}

func (x *OdaoNodes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdaoNodes.ProtoReflect.Descriptor instead.
func (*OdaoNodes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *OdaoNodes) GetNodeIds() [][]byte {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type SoloValidatorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoloValidatorsRequest) Reset() {
	*x = SoloValidatorsRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoloValidatorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoloValidatorsRequest) ProtoMessage() {}

func (x *SoloValidatorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoloValidatorsRequest.ProtoReflect.Descriptor instead.
func (*SoloValidatorsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

type SoloValidators struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalAddresses [][]byte               `protobuf:"bytes,1,rep,name=withdrawal_addresses,json=withdrawalAddresses,proto3" json:"withdrawal_addresses,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SoloValidators) Reset() {
	*x = SoloValidators{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoloValidators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoloValidators) ProtoMessage() {}

func (x *SoloValidators) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoloValidators.ProtoReflect.Descriptor instead.
func (*SoloValidators) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *SoloValidators) GetWithdrawalAddresses() [][]byte {
	if x != nil {
		return x.WithdrawalAddresses
	}
	return nil
}

type ValidateEIP1271Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataHash      []byte                 `protobuf:"bytes,1,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Address       []byte                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateEIP1271Request) Reset() {
	*x = ValidateEIP1271Request{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEIP1271Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEIP1271Request) ProtoMessage() {}

func (x *ValidateEIP1271Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEIP1271Request.ProtoReflect.Descriptor instead.
func (*ValidateEIP1271Request) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateEIP1271Request) GetDataHash() []byte {
	if x != nil {
		return x.DataHash
	}
	return nil
}

func (x *ValidateEIP1271Request) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ValidateEIP1271Request) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type ValidateEIP1271Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateEIP1271Response) Reset() {
	*x = ValidateEIP1271Response{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEIP1271Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEIP1271Response) ProtoMessage() {}

func (x *ValidateEIP1271Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEIP1271Response.ProtoReflect.Descriptor instead.
func (*ValidateEIP1271Response) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateEIP1271Response) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateEIP1271Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x02pb\"\x18\n" +
	"\x16RocketPoolNodesRequest\",\n" +
	"\x0fRocketPoolNodes\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\fR\anodeIds\"\x12\n" +
	"\x10OdaoNodesRequest\"&\n" +
	"\tOdaoNodes\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\fR\anodeIds\"\x17\n" +
	"\x15SoloValidatorsRequest\"C\n" +
	"\x0eSoloValidators\x121\n" +
	"\x14withdrawal_addresses\x18\x01 \x03(\fR\x13withdrawalAddresses\"m\n" +
	"\x16ValidateEIP1271Request\x12\x1b\n" +
	"\tdata_hash\x18\x01 \x01(\fR\bdataHash\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\fR\aaddress\"E\n" +
	"\x17ValidateEIP1271Response\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x99\x02\n" +
	"\x03Api\x12G\n" +
	"\x12GetRocketPoolNodes\x12\x1a.pb.RocketPoolNodesRequest\x1a\x13.pb.RocketPoolNodes\"\x00\x125\n" +
	"\fGetOdaoNodes\x12\x14.pb.OdaoNodesRequest\x1a\r.pb.OdaoNodes\"\x00\x12D\n" +
	"\x11GetSoloValidators\x12\x19.pb.SoloValidatorsRequest\x1a\x12.pb.SoloValidators\"\x00\x12L\n" +
	"\x0fValidateEIP1271\x12\x1a.pb.ValidateEIP1271Request\x1a\x1b.pb.ValidateEIP1271Response\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_goTypes = []any{
	(*RocketPoolNodesRequest)(nil),  // 0: pb.RocketPoolNodesRequest
	(*RocketPoolNodes)(nil),         // 1: pb.RocketPoolNodes
	(*OdaoNodesRequest)(nil),        // 2: pb.OdaoNodesRequest
	(*OdaoNodes)(nil),               // 3: pb.OdaoNodes
	(*SoloValidatorsRequest)(nil),   // 4: pb.SoloValidatorsRequest
	(*SoloValidators)(nil),          // 5: pb.SoloValidators
	(*ValidateEIP1271Request)(nil),  // 6: pb.ValidateEIP1271Request
	(*ValidateEIP1271Response)(nil), // 7: pb.ValidateEIP1271Response
}
var file_api_proto_depIdxs = []int32{
	0, // 0: pb.Api.GetRocketPoolNodes:input_type -> pb.RocketPoolNodesRequest
	2, // 1: pb.Api.GetOdaoNodes:input_type -> pb.OdaoNodesRequest
	4, // 2: pb.Api.GetSoloValidators:input_type -> pb.SoloValidatorsRequest
	6, // 3: pb.Api.ValidateEIP1271:input_type -> pb.ValidateEIP1271Request
	1, // 4: pb.Api.GetRocketPoolNodes:output_type -> pb.RocketPoolNodes
	3, // 5: pb.Api.GetOdaoNodes:output_type -> pb.OdaoNodes
	5, // 6: pb.Api.GetSoloValidators:output_type -> pb.SoloValidators
	7, // 7: pb.Api.ValidateEIP1271:output_type -> pb.ValidateEIP1271Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
